<?php

namespace Database\Seeders;

use App\Models\User;
use App\PermissionName;
use App\RoleName;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissionRegistrar = app(PermissionRegistrar::class);
        $permissionRegistrar->forgetCachedPermissions();

        foreach (PermissionName::cases() as $permission) {
            Permission::findOrCreate($permission->value, 'web');
        }

        $permissionRegistrar->forgetCachedPermissions();

        foreach ($this->rolePermissions() as $roleName => $permissions) {
            Role::findOrCreate($roleName, 'web')->syncPermissions($permissions);
        }

        User::query()
            ->whereDoesntHave('roles')
            ->lazyById()
            ->each(function (User $user): void {
                $user->assignRole(match ($user->role) {
                    'admin' => RoleName::NbtsAdmin->value,
                    'staff' => RoleName::CenterStaff->value,
                    default => RoleName::Donor->value,
                });
            });

        $permissionRegistrar->forgetCachedPermissions();
    }

    /**
     * @return array<string, list<string>>
     */
    private function rolePermissions(): array
    {
        return [
            RoleName::SuperAdmin->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ManageUsers,
                PermissionName::ManageRoles,
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ManageDonors,
                PermissionName::ViewCenters,
                PermissionName::ManageCenters,
                PermissionName::ManageCenterStaff,
                PermissionName::ViewAppointments,
                PermissionName::ManageAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ManageDeferrals,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewCampaigns,
                PermissionName::ManageCampaigns,
                PermissionName::ViewArticles,
                PermissionName::ManageArticles,
                PermissionName::ManageNotifications,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ManageLoyalty,
                PermissionName::ViewAudits,
                PermissionName::ManageBackups,
                PermissionName::ManageSettings,
                PermissionName::ViewOrganizations,
                PermissionName::ManageOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ManageDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ManageAssignments,
                PermissionName::ApproveAssignments,
                PermissionName::ViewSystemHealth,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageDataProtection,
                PermissionName::ManageIntegrations,
                PermissionName::ManageSecurityOperations,
                PermissionName::ManageChangeControls,
                PermissionName::ManageIncidents,
            ]),
            RoleName::NbtsAdmin->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ManageDonors,
                PermissionName::ReviewDonorDuplicates,
                PermissionName::ViewCenters,
                PermissionName::ManageCenters,
                PermissionName::ManageCenterStaff,
                PermissionName::ViewAppointments,
                PermissionName::ManageAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ManageDeferrals,
                PermissionName::ManageScreeningProtocols,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewCampaigns,
                PermissionName::ManageCampaigns,
                PermissionName::ViewArticles,
                PermissionName::ManageArticles,
                PermissionName::ManageNotifications,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ManageLoyalty,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ManageOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ManageDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ManageAssignments,
                PermissionName::ManageOfflineCollectionDevices,
                PermissionName::ReconcileOfflineCollections,
            ]),
            RoleName::CenterManager->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ManageDonors,
                PermissionName::ReviewDonorDuplicates,
                PermissionName::ConfirmDonorIdentity,
                PermissionName::ViewCenters,
                PermissionName::ManageCenterStaff,
                PermissionName::ViewAppointments,
                PermissionName::ManageAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ManageDeferrals,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::PrepareCollections,
                PermissionName::ManageCollectionLabels,
                PermissionName::HandOffSpecimens,
                PermissionName::RecordDonorReactions,
                PermissionName::ManageOfflineCollectionDevices,
                PermissionName::ReconcileOfflineCollections,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewCampaigns,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ManageAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewQuality,
            ]),
            RoleName::CenterStaff->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ConfirmDonorIdentity,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::PrepareCollections,
                PermissionName::ManageCollectionLabels,
                PermissionName::HandOffSpecimens,
                PermissionName::RecordDonorReactions,
                PermissionName::ReconcileOfflineCollections,
                PermissionName::ViewInventory,
            ]),
            RoleName::Donor->value => [],
            RoleName::IctSecurityOperator->value => $this->values([
                PermissionName::ViewOrganizations,
                PermissionName::ViewSystemHealth,
                PermissionName::ViewReports,
                PermissionName::ViewAudits,
                PermissionName::ManageBackups,
                PermissionName::ManageSettings,
                PermissionName::ManageIntegrations,
                PermissionName::ManageSecurityOperations,
                PermissionName::ManageIncidents,
                PermissionName::ManageChangeControls,
            ]),
            RoleName::NationalOperationsAdministrator->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ManageDonors,
                PermissionName::ReviewDonorDuplicates,
                PermissionName::ViewCenters,
                PermissionName::ManageCenters,
                PermissionName::ManageCenterStaff,
                PermissionName::ViewAppointments,
                PermissionName::ManageAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ManageDeferrals,
                PermissionName::ManageScreeningProtocols,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewCampaigns,
                PermissionName::ManageCampaigns,
                PermissionName::ManageNotifications,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ManageOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ManageDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ManageAssignments,
                PermissionName::ManageOfflineCollectionDevices,
                PermissionName::ReconcileOfflineCollections,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageIncidents,
                PermissionName::ManageChangeControls,
            ]),
            RoleName::NationalQualityHaemovigilanceOfficer->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewCampaigns,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageQuality,
                PermissionName::ManageHaemovigilance,
                PermissionName::ManageRecalls,
                PermissionName::ManageIncidents,
                PermissionName::ManageChangeControls,
            ]),
            RoleName::NationalInventoryLogisticsCoordinator->value => $this->values([
                PermissionName::ViewCenters,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ManageLogistics,
                PermissionName::ManageColdChain,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
            ]),
            RoleName::NationalDonorEngagementContentOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewCampaigns,
                PermissionName::ManageCampaigns,
                PermissionName::ViewArticles,
                PermissionName::ManageArticles,
                PermissionName::ManageNotifications,
                PermissionName::ManageLoyalty,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
            ]),
            RoleName::DataProtectionGovernanceOfficer->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewArticles,
                PermissionName::ViewReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageDataProtection,
                PermissionName::ManageChangeControls,
                PermissionName::ManageIncidents,
            ]),
            RoleName::NationalAuditorInspector->value => $this->values([
                PermissionName::ViewUsers,
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewCampaigns,
                PermissionName::ViewArticles,
                PermissionName::ViewReports,
                PermissionName::ViewAudits,
                PermissionName::ViewOrganizations,
                PermissionName::ViewDepartments,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
            ]),
            RoleName::ReceptionOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::RegisterDonors,
                PermissionName::ManageDonors,
                PermissionName::ReviewDonorDuplicates,
                PermissionName::ConfirmDonorIdentity,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ManageAppointments,
            ]),
            RoleName::ScreeningCounsellingOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ConfirmDonorIdentity,
                PermissionName::CheckEligibility,
                PermissionName::ManageDeferrals,
                PermissionName::ViewReports,
                PermissionName::ViewQuality,
            ]),
            RoleName::CollectionPhlebotomyOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ConfirmDonorIdentity,
                PermissionName::CheckEligibility,
                PermissionName::ViewDonations,
                PermissionName::RecordDonations,
                PermissionName::PrepareCollections,
                PermissionName::ManageCollectionLabels,
                PermissionName::HandOffSpecimens,
                PermissionName::RecordDonorReactions,
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewQuality,
            ]),
            RoleName::LaboratoryTechnician->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewLaboratory,
                PermissionName::RecordLaboratoryTests,
                PermissionName::ViewComponents,
                PermissionName::ViewQuality,
            ]),
            RoleName::LaboratoryApproverQualityOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewLaboratory,
                PermissionName::ApproveLaboratoryRelease,
                PermissionName::ViewComponents,
                PermissionName::ViewQuality,
                PermissionName::ManageQuality,
            ]),
            RoleName::ComponentProcessingOfficer->value => $this->values([
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ProcessComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewQuality,
            ]),
            RoleName::InventoryOfficer->value => $this->values([
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ManageInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewQuality,
            ]),
            RoleName::LogisticsColdChainOfficer->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ManageInventoryTransfers,
                PermissionName::ViewReports,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ManageLogistics,
                PermissionName::ManageColdChain,
                PermissionName::ViewQuality,
            ]),
            RoleName::CenterHaemovigilanceQualityOfficer->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::CheckEligibility,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewCampaigns,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageQuality,
                PermissionName::ManageHaemovigilance,
                PermissionName::ManageRecalls,
            ]),
            RoleName::CenterReadOnlyAuditor->value => $this->values([
                PermissionName::ViewDonors,
                PermissionName::ViewCenters,
                PermissionName::ViewAppointments,
                PermissionName::ViewDonations,
                PermissionName::ViewInventory,
                PermissionName::ViewCampaigns,
                PermissionName::ViewArticles,
                PermissionName::ViewReports,
                PermissionName::ViewAudits,
                PermissionName::ViewAssignments,
                PermissionName::ViewLaboratory,
                PermissionName::ViewComponents,
                PermissionName::ViewLogistics,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
            ]),
            RoleName::HospitalClinicianRequester->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewHospitalRequests,
                PermissionName::ManageHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageHaemovigilance,
            ]),
            RoleName::HospitalBloodBankOfficer->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewHospitalRequests,
                PermissionName::ManageHospitalRequests,
                PermissionName::ManageBloodIssue,
                PermissionName::ViewQuality,
                PermissionName::ManageHaemovigilance,
            ]),
            RoleName::CompatibilityCrossmatchOfficer->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewHospitalRequests,
                PermissionName::ManageCompatibility,
                PermissionName::ViewQuality,
            ]),
            RoleName::TransfusionNurseOfficer->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewHospitalRequests,
                PermissionName::RecordTransfusions,
                PermissionName::ViewQuality,
                PermissionName::ManageHaemovigilance,
            ]),
            RoleName::HospitalHaemovigilanceOfficer->value => $this->values([
                PermissionName::ViewReports,
                PermissionName::ExportReports,
                PermissionName::ViewAudits,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
                PermissionName::ManageQuality,
                PermissionName::ManageHaemovigilance,
                PermissionName::ManageRecalls,
            ]),
            RoleName::HospitalReadOnlyReviewer->value => $this->values([
                PermissionName::ViewInventory,
                PermissionName::ViewReports,
                PermissionName::ViewAudits,
                PermissionName::ViewHospitalRequests,
                PermissionName::ViewQuality,
            ]),
        ];
    }

    /**
     * @param  list<PermissionName>  $permissions
     * @return list<string>
     */
    private function values(array $permissions): array
    {
        return array_map(
            static fn (PermissionName $permission): string => $permission->value,
            $permissions,
        );
    }
}
