<?php

return [
    'brand' => 'National Blood Transfusion Service',
    'confidential' => 'Confidential NBTS record',
    'generated_at' => 'Generated at',
    'generated_by' => 'Generated by',
    'page' => 'Page :current of :total',
    'donor_card' => 'Donor card',
    'donation_certificate' => 'Blood donation certificate',
    'donation_history' => 'Donation history',
    'inventory_report' => 'Blood inventory report',
    'audit_report' => 'Audit trail report',
    'center' => 'Blood center',
    'donor' => 'Donor',
    'date' => 'Date',
    'status' => 'Status',
    'reference' => 'Reference',
];
