<?php

use App\PermissionName;

return [
    'configurations' => [
        'system_control' => [
            'title' => 'console.dashboards.system_control.title',
            'description' => 'console.dashboards.system_control.description',
            'eyebrow' => 'console.dashboards.system_control.eyebrow',
            'accent' => 'plum',
            'metrics' => ['active_users', 'active_assignments', 'organization_units', 'audits_today'],
            'links' => [
                ['workspace' => 'administration', 'tab' => 'users', 'icon' => 'shield-check', 'permission' => PermissionName::ViewUsers->value],
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
            ],
        ],
        'national_operations' => [
            'title' => 'console.dashboards.national_operations.title',
            'description' => 'console.dashboards.national_operations.description',
            'eyebrow' => 'console.dashboards.national_operations.eyebrow',
            'accent' => 'red',
            'metrics' => ['active_centers', 'active_assignments', 'appointments_today', 'donations_today'],
            'links' => [
                ['workspace' => 'appointments', 'tab' => 'today', 'icon' => 'calendar-clock', 'permission' => PermissionName::ViewAppointments->value],
                ['workspace' => 'response', 'tab' => 'low_stock_alerts', 'icon' => 'siren', 'permission' => PermissionName::ViewCampaigns->value],
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
            ],
        ],
        'national_quality_governance' => [
            'title' => 'console.dashboards.national_quality_governance.title',
            'description' => 'console.dashboards.national_quality_governance.description',
            'eyebrow' => 'console.dashboards.national_quality_governance.eyebrow',
            'accent' => 'indigo',
            'metrics' => ['audits_today', 'active_deferrals', 'open_alerts', 'competencies_expiring'],
            'links' => [
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
                ['workspace' => 'administration', 'tab' => 'audit', 'icon' => 'shield-check', 'permission' => PermissionName::ViewAudits->value],
            ],
        ],
        'national_inventory_logistics' => [
            'title' => 'console.dashboards.national_inventory_logistics.title',
            'description' => 'console.dashboards.national_inventory_logistics.description',
            'eyebrow' => 'console.dashboards.national_inventory_logistics.eyebrow',
            'accent' => 'blue',
            'metrics' => ['available_units', 'reserved_units', 'testing_queue', 'open_alerts'],
            'links' => [
                ['workspace' => 'blood-operations', 'tab' => 'inventory', 'icon' => 'package-check', 'permission' => PermissionName::ViewInventory->value],
                ['workspace' => 'response', 'tab' => 'low_stock_alerts', 'icon' => 'siren', 'permission' => PermissionName::ViewCampaigns->value],
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
            ],
        ],
        'engagement_content' => [
            'title' => 'console.dashboards.engagement_content.title',
            'description' => 'console.dashboards.engagement_content.description',
            'eyebrow' => 'console.dashboards.engagement_content.eyebrow',
            'accent' => 'rose',
            'metrics' => ['active_donors', 'active_campaigns', 'published_articles', 'notifications_today'],
            'links' => [
                ['workspace' => 'engagement', 'tab' => 'notifications', 'icon' => 'heart-handshake', 'permission' => PermissionName::ManageNotifications->value],
                ['workspace' => 'content', 'tab' => 'news', 'icon' => 'newspaper', 'permission' => PermissionName::ViewArticles->value],
                ['workspace' => 'response', 'tab' => 'campaigns', 'icon' => 'siren', 'permission' => PermissionName::ViewCampaigns->value],
            ],
        ],
        'center_management' => [
            'title' => 'console.dashboards.center_management.title',
            'description' => 'console.dashboards.center_management.description',
            'eyebrow' => 'console.dashboards.center_management.eyebrow',
            'accent' => 'red',
            'metrics' => ['appointments_today', 'donations_today', 'active_assignments', 'open_alerts'],
            'links' => [
                ['workspace' => 'appointments', 'tab' => 'today', 'icon' => 'calendar-clock', 'permission' => PermissionName::ViewAppointments->value],
                ['workspace' => 'eligibility', 'tab' => 'screening_queue', 'icon' => 'clipboard-check', 'permission' => PermissionName::CheckEligibility->value],
                ['workspace' => 'blood-operations', 'tab' => 'inventory', 'icon' => 'package-check', 'permission' => PermissionName::ViewInventory->value],
                ['workspace' => 'response', 'tab' => 'low_stock_alerts', 'icon' => 'siren', 'permission' => PermissionName::ViewCampaigns->value],
            ],
        ],
        'reception' => [
            'title' => 'console.dashboards.reception.title',
            'description' => 'console.dashboards.reception.description',
            'eyebrow' => 'console.dashboards.reception.eyebrow',
            'accent' => 'amber',
            'metrics' => ['appointments_today', 'pending_appointments', 'checked_in_today', 'active_donors'],
            'links' => [
                ['workspace' => 'donor-reception', 'tab' => 'search', 'icon' => 'scan-line', 'permission' => PermissionName::ViewDonors->value],
                ['workspace' => 'appointments', 'tab' => 'today', 'icon' => 'calendar-clock', 'permission' => PermissionName::ViewAppointments->value],
            ],
        ],
        'screening_counselling' => [
            'title' => 'console.dashboards.screening_counselling.title',
            'description' => 'console.dashboards.screening_counselling.description',
            'eyebrow' => 'console.dashboards.screening_counselling.eyebrow',
            'accent' => 'teal',
            'metrics' => ['pending_screening', 'screenings_today', 'active_deferrals', 'appointments_today'],
            'links' => [
                ['workspace' => 'eligibility', 'tab' => 'screening_queue', 'icon' => 'clipboard-check', 'permission' => PermissionName::CheckEligibility->value],
                ['workspace' => 'donor-reception', 'tab' => 'search', 'icon' => 'scan-line', 'permission' => PermissionName::ViewDonors->value],
            ],
        ],
        'collection' => [
            'title' => 'console.dashboards.collection.title',
            'description' => 'console.dashboards.collection.description',
            'eyebrow' => 'console.dashboards.collection.eyebrow',
            'accent' => 'red',
            'metrics' => ['ready_for_collection', 'donations_today', 'testing_queue', 'available_units'],
            'links' => [
                ['workspace' => 'donations', 'tab' => 'record', 'icon' => 'droplets', 'permission' => PermissionName::RecordDonations->value],
                ['workspace' => 'appointments', 'tab' => 'today', 'icon' => 'calendar-clock', 'permission' => PermissionName::ViewAppointments->value],
            ],
        ],
        'laboratory_components' => [
            'title' => 'console.dashboards.laboratory_components.title',
            'description' => 'console.dashboards.laboratory_components.description',
            'eyebrow' => 'console.dashboards.laboratory_components.eyebrow',
            'accent' => 'violet',
            'metrics' => ['testing_queue', 'released_units', 'expiring_units', 'open_alerts'],
            'links' => [
                ['workspace' => 'blood-operations', 'tab' => 'testing_queue', 'icon' => 'test-tubes', 'permission' => PermissionName::ViewInventory->value],
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
            ],
        ],
        'center_inventory_logistics' => [
            'title' => 'console.dashboards.center_inventory_logistics.title',
            'description' => 'console.dashboards.center_inventory_logistics.description',
            'eyebrow' => 'console.dashboards.center_inventory_logistics.eyebrow',
            'accent' => 'blue',
            'metrics' => ['available_units', 'reserved_units', 'expiring_units', 'open_alerts'],
            'links' => [
                ['workspace' => 'blood-operations', 'tab' => 'inventory', 'icon' => 'package-check', 'permission' => PermissionName::ViewInventory->value],
                ['workspace' => 'blood-operations', 'tab' => 'transfers', 'icon' => 'package-check', 'permission' => PermissionName::ManageInventoryTransfers->value],
            ],
        ],
        'center_quality_haemovigilance' => [
            'title' => 'console.dashboards.center_quality_haemovigilance.title',
            'description' => 'console.dashboards.center_quality_haemovigilance.description',
            'eyebrow' => 'console.dashboards.center_quality_haemovigilance.eyebrow',
            'accent' => 'indigo',
            'metrics' => ['audits_today', 'active_deferrals', 'competencies_expiring', 'open_alerts'],
            'links' => [
                ['workspace' => 'intelligence', 'tab' => 'reports', 'icon' => 'chart-no-axes-combined', 'permission' => PermissionName::ViewReports->value],
                ['workspace' => 'response', 'tab' => 'low_stock_alerts', 'icon' => 'siren', 'permission' => PermissionName::ViewCampaigns->value],
            ],
        ],
        'hospital_operations' => [
            'title' => 'console.dashboards.hospital_operations.title',
            'description' => 'console.dashboards.hospital_operations.description',
            'eyebrow' => 'console.dashboards.hospital_operations.eyebrow',
            'accent' => 'emerald',
            'metrics' => ['organization_units', 'active_assignments', 'current_competencies', 'audits_today'],
            'links' => [],
            'readiness' => 'console.dashboards.hospital_operations.readiness',
        ],
    ],
    'metric_icons' => [
        'active_users' => 'badge-check',
        'active_assignments' => 'badge-check',
        'organization_units' => 'map-pin',
        'audits_today' => 'shield-check',
        'active_centers' => 'map-pin',
        'appointments_today' => 'calendar-clock',
        'donations_today' => 'droplets',
        'active_deferrals' => 'clipboard-check',
        'open_alerts' => 'siren',
        'competencies_expiring' => 'shield-check',
        'available_units' => 'package-check',
        'reserved_units' => 'package-check',
        'testing_queue' => 'test-tubes',
        'active_donors' => 'heart-handshake',
        'active_campaigns' => 'siren',
        'published_articles' => 'newspaper',
        'notifications_today' => 'activity',
        'pending_appointments' => 'calendar-clock',
        'checked_in_today' => 'calendar-clock',
        'pending_screening' => 'clipboard-check',
        'screenings_today' => 'clipboard-check',
        'ready_for_collection' => 'circle-check',
        'released_units' => 'shield-check',
        'expiring_units' => 'calendar-clock',
        'current_competencies' => 'shield-check',
    ],
];
